Добавлены обработчики на клики по кнопкам favourite, watchlist, history
htmlacademy-ecmascript/968667-cinemaddict-12 pull request #6
Opened 2020-09-02 14:06 UTC by StasyaV

2020-09-06 18:59 UTC, andreevsm requested changes

2020-09-06 18:59 UTC, andreevsm commented on src/view/film-details.js
> +    let clickedElement = evt.target.value;
1. Это же не элемент, а выбранная эмодзи
2. const

2020-09-06 18:59 UTC, andreevsm commented on src/view/film-details.js
> +      this.getElement().querySelector(`.film-details__add-emoji-label`).insertAdjacentHTML(RenderPosition.AFTERBEGIN, imgElement);
insertAdjacentHTML - у тебя разве в утилитах не было функции с таким же методом?

2020-09-06 18:59 UTC, andreevsm commented on src/view/film-details.js
> +      let imgElement = `<img src="./images/emoji/${clickedElement}.png" width="55" height="55" alt="emoji-smile">`;
const

2020-09-06 18:59 UTC, andreevsm commented on src/view/film-card.js
> +
Лишний отступ

2020-09-06 18:59 UTC, andreevsm commented on src/view/smart.js
> +
А здесь не подойдет функция `replace`? Очень похожий код

2020-09-07 07:39 UTC, StasyaV commented on src/view/smart.js
> +
Делала по аналогии с учебным) Там реализовано так)

2020-09-07 13:56 UTC, merged